version: '2'

services:
  sm:
    build:
      context: .
    restart: on-failure:5
    volumes:
      - ./sm:/sm
    env_file:
      - ./.env
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - "db:db"

  db:
    image: postgres:9.6
    restart: on-failure:5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - sm_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: on-failure:5
    ports:
      - 8080:8080

volumes:
  sm_db:
